// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// ...

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYjMjVZ1-lDQj76gZ-7J9t4a87IB0gSac',
    appId: '1:1023007381747:web:da6db0c342c0a5aac3bf86',
    messagingSenderId: '1023007381747',
    projectId: 'satietyapp',
    authDomain: 'satietyapp.firebaseapp.com',
    storageBucket: 'satietyapp.appspot.com',
    measurementId: 'G-VWX1752DYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFkgk7N-JkiLHOEDowS6LH7q-bIP1nRF0',
    appId: '1:1023007381747:android:8150ffeaafc8c5c5c3bf86',
    messagingSenderId: '1023007381747',
    projectId: 'satietyapp',
    storageBucket: 'satietyapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK9dhgh0NNMui_aQdY6QMqlDKkjCeygGs',
    appId: '1:1023007381747:ios:4d2997d9c0e156c9c3bf86',
    messagingSenderId: '1023007381747',
    projectId: 'satietyapp',
    storageBucket: 'satietyapp.appspot.com',
    iosClientId:
        '1023007381747-ahvolvc0e040la04i8blabso4a8kdp18.apps.googleusercontent.com',
    iosBundleId: 'com.example.satietyfrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK9dhgh0NNMui_aQdY6QMqlDKkjCeygGs',
    appId: '1:1023007381747:ios:4d2997d9c0e156c9c3bf86',
    messagingSenderId: '1023007381747',
    projectId: 'satietyapp',
    storageBucket: 'satietyapp.appspot.com',
    iosClientId:
        '1023007381747-ahvolvc0e040la04i8blabso4a8kdp18.apps.googleusercontent.com',
    iosBundleId: 'com.example.satietyfrontend',
  );
}
